### PR TITLE
fix gpu memory leak

### PR DESCRIPTION
**Pull request by makc**
an obvious one at that

### CODE REVIEW

**Comment by makc** [comment]
ha ha shit, it closed the PR. how do I re-open it? the PR is still good.

**Comment by makc** [comment]
ha ha shit, it closed the PR. how do I re-open it? the PR is still good.

**Comment by makc** [comment]
a-ha!

**Comment by makc** [comment]
I press `Reopen and comment` but it will only post a comment 😭

**Comment by EthanHermsey** [comment]
'ha ha shit, it closed the PR'. Aah, that's why I couldn't find it all this time :p (I did get an email)

Thanks for the mention! I revisited the code lately and added your suggestion. Now geometries are properly disposed :)

**Pull request closed without merging**
